---
title: "fyp_study1"
author: "Jinxiao Zhang"
date: "April 5, 2019"
output: html_document
---

```{r library}
library(tidyverse)
library(lubridate)

```

```{r prepare data}
# Eligibility: SUID, age, race, gender, gender_other, prsri_1-8, psqi_1-6, meq_19, erq
df.eligibility <- read_csv("psych1_data/Fall 2018 Eligibility Survey.csv", col_names = T) %>% 
  select(SUID, "Start Date", age, race, gender, gender_other, 
         starts_with("prsri"), starts_with("psqi"), 
         starts_with("meq"), starts_with("erq")) %>% 
  filter(row_number() > 1) %>% 
  # remove variable questions which is incorrectly in the data
  group_by(SUID) %>% 
  filter(row_number() == n()) # remove duplicates
  #only include the last response from the same participant


# Composite: SUID, age, race, gender, gender_other, pers, erqse
df.composite <- read_csv("psych1_data/Fall18 Composite Survey.csv", col_names = T) %>% 
  select(SUID, age, race, gender, gender_other, 
         starts_with("pers"), starts_with("erqse")) %>% 
  filter(row_number() > 1) # remove variable questions which is incorrectly in the data

# combine the dataset
df.questionnaire <- df.eligibility %>% 
  left_join(df.composite %>% select(SUID, starts_with("pers"), starts_with("erqse")),
            by = "SUID") %>% 
  ungroup() %>% 
  select(-SUID) %>% 
  mutate(participant = sprintf("%04d", row_number())) %>% 
  select(participant, everything())

# write the data file to csv
write_csv(df.questionnaire, "data/data_questionnaire.csv", na = "")

## variable names
# prsri - PROMIS sleep-related impairment
# psqi - Pittsburgh sleep quality index
# erqf - emotion regulation frequency
# pers - Perth Reactivity Scale 
# erqse - emotion regulation self-efficacy

```

## Jonas' code - add your code here and below
## for cleaning up workspace (rm(list=ls()))
## Copy of the original file (creating a working file [wf])
```{r}

raw_data <- read.csv("data/data_questionnaire.csv")

wf <-raw_data


```

## viewing data (getting a sense of the df)

```{r}
wf %>% 
  head() %>% 
  View()
```

## quesstionnaire PRSRI (PROMIS sleep-related impairment)

```{r}
## Changing Likert scale into numeric values

##understanding the type of prsri rn

str(wf$prsri_1:wf$prsri_8, 
    digits.d = 1)

class(wf$prsri_1:wf$prsri_8)
levels(wf$prsri_1:wf$prsri_8)

## Start mutating like a mad man
## Not at all (1), A little bit (2), Somewhat (3), Quite a bit (4), Very much (5)

wf1 <- wf
wf1 <- wf1 %>% 
  mutate(prsri_1 = case_when(
    wf$prsri_1 == "Not at all"~ "1",
    wf$prsri_1 == "Somewhat"~ "2",
    wf$prsri_1 == "Quite a bit"~ "3",
    wf$prsri_1 == "A little bit"~ "4",
    wf$prsri_1 == "Very much"~ "5",
    wf$prsri_1 == ""~ "-1",
))
wf1$prsri_1 <- as.numeric(wf1$prsri_1)
str(wf1$prsri_1)

wf1 <- wf1 %>% 
  mutate(prsri_2 = case_when(
    wf$prsri_2 == "Not at all"~ "1",
    wf$prsri_2 == "Somewhat"~ "2",
    wf$prsri_2 == "Quite a bit"~ "3",
    wf$prsri_2 == "A little bit"~ "4",
    wf$prsri_2 == "Very much"~ "5",
    wf$prsri_2 == ""~ "-1",
))

wf1$prsri_2 <- as.numeric(wf1$prsri_2)
str(wf1$prsri_1)
wf1 <- wf1

wf1 <- wf1 %>%  
  mutate(prsri_3 = case_when(
    wf$prsri_3 == "Not at all"~ "1",
    wf$prsri_3 == "Somewhat"~ "2",
    wf$prsri_3 == "Quite a bit"~ "3",
    wf$prsri_3 == "A little bit"~ "4",
    wf$prsri_3 == "Very much"~ "5",
    wf$prsri_3 == ""~ "-1",
))
wf1$prsri_3 <- as.numeric(wf1$prsri_3)
str(wf1$prsri_3)

wf1 <- wf1 %>% 
  mutate(prsri_4 = case_when(
    wf$prsri_4 == "Not at all"~ "1",
    wf$prsri_4 == "Somewhat"~ "2",
    wf$prsri_4 == "Quite a bit"~ "3",
    wf$prsri_4 == "A little bit"~ "4",
    wf$prsri_4 == "Very much"~ "5",
    wf$prsri_4 == ""~ "-1",
))
wf1$prsri_4 <-as.numeric(wf1$prsri_4)
str(wf1$prsri_4)

wf1 <- wf1 %>% 
  mutate(prsri_5 = case_when(
    wf$prsri_5 == "Not at all"~ "1",
    wf$prsri_5 == "Somewhat"~ "2",
    wf$prsri_5 == "Quite a bit"~ "3",
    wf$prsri_5 == "A little bit"~ "4",
    wf$prsri_5 == "Very much"~ "5",
    wf$prsri_5 == ""~ "-1",
))
wf1$prsri_5 <-as.numeric(wf1$prsri_5)
str(wf1$prsri_5)
wf1 <- wf1

wf1 <- wf1 %>% 
  mutate(prsri_6 = case_when(
    wf$prsri_6 == "Not at all"~ "1",
    wf$prsri_6 == "Somewhat"~ "2",
    wf$prsri_6 == "Quite a bit"~ "3",
    wf$prsri_6 == "A little bit"~ "4",
    wf$prsri_6 == "Very much"~ "5",
    wf$prsri_6 == ""~ "-1",
))
wf1$prsri_6 <-as.numeric(wf1$prsri_6)
str(wf1$prsri_6)
wf1 <- wf1

wf1 <- wf1 %>% 
  mutate(prsri_7 = case_when(
    wf$prsri_7 == "Not at all"~ "1",
    wf$prsri_7 == "Somewhat"~ "2",
    wf$prsri_7 == "Quite a bit"~ "3",
    wf$prsri_7 == "A little bit"~ "4",
    wf$prsri_7 == "Very much"~ "5",
    wf$prsri_7 == ""~ "-1",
))
wf1$prsri_7 <-as.numeric(wf1$prsri_7)
str(wf1$prsri_7)
wf1 <- wf1

wf1 <- wf1 %>% 
  mutate(prsri_8 = case_when(
    wf$prsri_8 == "Not at all"~ "1",
    wf$prsri_8 == "Somewhat"~ "2",
    wf$prsri_8 == "Quite a bit"~ "3",
    wf$prsri_8 == "A little bit"~ "4",
    wf$prsri_8 == "Very much"~ "5",
    wf$prsri_8 == ""~ "-1"
))
wf1$prsri_8 <-as.numeric(wf1$prsri_8)
str(wf1$prsri_8)
wf1 <- wf1


wf1$prsri_all <- wf1$prsri_1 + wf1$prsri_2 + wf1$prsri_3 + wf1$prsri_4 + wf1$prsri_5 + wf1$prsri_6


### Finding out it works (PROMIS)
promis.df <- wf1 %>% 
  select(prsri_1:prsri_8, prsri_all) %>% 
  head()
  




```



## quesstionnaire psqi - Pittsburgh sleep quality index

```{r}
wf2 <- wf1

  wf2 %>% 
    select(starts_with("psqi"))
## transforming time into miliary time for later calculation
## evening_time (if am than 12 - x) - morning_time = TST


wf2$psqi_1_hour <- as.numeric(wf2$psqi_1_hour)
 
wf2$psqi_1_min <- as.numeric(wf2$psqi_1_min)

wf2$psqi_3_hour <- as.numeric(wf2$psqi_3_hour)
 
wf2$psqi_3_min <- as.numeric(wf2$psqi_3_min)
wf2 <- wf2


wf2 <- wf2 %>%
  mutate(psqi_1_hour_MT = psqi_1_hour + 12)

wf2$psqi_1_hour_MT[wf2$psqi_1_ampm == 'AM'] = wf2$psqi_1_hour_MT[wf2$psqi_1_ampm == 'AM'] - 12

##changing the 12am people to 0, because thats how military time works. It starts at 0 not 12.

wf2$psqi_1_hour_MT[wf2$psqi_1_hour== 12] = 0

wf2 <- wf2

## transforming it into min since last midnight in order to avoid min/h calculation problems while substracting
## adding the min from another variable

wf2$psqi_1_hour_MT_min = (wf2$psqi_1_hour_MT *60) + wf2$psqi_1_min


## to calculate the time slept until midnight (for example if someone felt asleep at 22:00, he slept 2h until mitnight and then I just add the minutes to the wake up), it will also be in minutes thats why 24 * 60 = 1440 ...lol

wf2$psqi_timetillmidnight [wf2$psqi_1_ampm == 'PM'] <-  (24*60) - wf2$psqi_1_hour_MT_min [wf2$psqi_1_ampm == 'PM']

##Sleep from midnight to morning RELEVANT FOR AM AND PM!!!

wf2$psqi_timetillwakeup <- (wf2$psqi_3_hour * 60) + wf2$psqi_3_min

##Time spend in bed (PM) = time till midnight + time until wakey wakey 

wf2$psqi_time_in_bed_pm <-  wf2$psqi_timetillmidnight + wf2$psqi_timetillwakeup 

## AM sleepers will be calculated by the difference between time until midnight when they fell asleep to their wake up

wf2$psqi_timeaftermidnight [wf2$psqi_1_ampm == 'AM'] <- wf2$psqi_1_hour_MT

## time in bed wakeup time - time of falling asleep after midnight

wf2$psqi_time_in_bed_am <- wf2$psqi_timetillwakeup - wf2$psqi_timeaftermidnight

## bringing am and pm together

wf2 <- wf2 %>%
  mutate(psqi_time_in_bed_min = case_when(
   wf2$psqi_1_ampm == 'AM'~ wf2$psqi_time_in_bed_am,
   wf2$psqi_1_ampm == 'PM'~ wf2$psqi_time_in_bed_pm
  ))

wf2$psqi_time_in_bed_h <- wf2$psqi_time_in_bed_min / 60

### COMPONENTS ########################
#####################

###Component 1: Subjective sleep quality-question 9 (for us psqi_6)

wf2 <- wf2 %>% 
  mutate(psqi_sq_c1 = case_when(
    wf2$psqi_6 == "Very good"~ "0",
    wf2$psqi_6 == "Fairly good"~ "1",
    wf2$psqi_6 == "Fairly bad"~ "2",
    wf2$psqi_6 == "Very bad"~ "3",
    wf2$psqi_6 == "" ~ "-1",
  ))

wf2$psqi_sq_c1 <- as.numeric(wf2$psqi_sq_c1)

###Component 2: Sleep latency-questions 2 and 5a

wf2 <- wf2 %>% 
  mutate(psqi_latency_a = case_when(
    wf2$psqi_2 < 16 ~ "0",
    wf2$psqi_2 > 15 & wf2$psqi_2 < 31 ~ "1",
    wf2$psqi_2 > 30 & wf2$psqi_2 < 61 ~ "2",
    wf2$psqi_2 > 60 ~ "3",
    wf2$psqi_2 == "" ~ "-1",
  ))

wf2$psqi_latency_a <- as.numeric(wf2$psqi_latency_a)

wf2 <- wf2 %>% 
  mutate(psqi_latency_b = case_when(
    wf2$psqi_5a == "Less than once a week" ~ "1",
    wf2$psqi_5a == "Not during the past month" ~ "0",
    wf2$psqi_5a == "Once or twice a week" ~ "2",
    wf2$psqi_5a == "Three or more times a week" ~ "3",
    wf2$psqi_5a == "" ~ "-1",
  ))

wf2$psqi_latency_b <- as.numeric(wf2$psqi_latency_b)

wf2$psqi_latency_ab <- wf2$psqi_latency_b + wf2$psqi_latency_a

wf2 <- wf2 %>% 
  mutate(psqi_latency_c2 = case_when(
    wf2$psqi_latency_ab == 0 ~ "0",
    wf2$psqi_latency_ab > 0 & wf2$psqi_latency_ab < 3 ~ "1",
    wf2$psqi_latency_ab > 2 & wf2$psqi_latency_ab < 5 ~ "2",
    wf2$psqi_latency_ab > 4 ~ "3"
  ))

####Component 3: Sleep duration-question 4
    
wf2 %>% 
    select(starts_with("psqi"))

```

